const { Random } = require('../models');

const randomData = [

    {random_word: 'ba'},{random_word: 'baa'},{random_word: 'babe'},{random_word: 'baby'},{random_word: 'baccalaureate'},{random_word: 'baccalaureates'},{random_word: 'bacchanalians'},{random_word: 'bach'},{random_word: 'bachelor'},{random_word: 'bachelorette'},{random_word: 'bachelorettes'},{random_word: 'bachelorhoods'},{random_word: 'bailey'},{random_word: 'bait'},{random_word: 'bake'},
    {random_word: 'bacillus'},{random_word: 'back'},{random_word: 'backboard'},{random_word: 'backbone'},{random_word: 'backbreaking'},{random_word: 'backcountries'},{random_word: 'backcountry'},{random_word: 'backcourt'},{random_word: 'backdoor'},{random_word: 'backdrop'},{random_word: 'backed'},{random_word: 'backfield'},{random_word: 'ball'},{random_word: 'ballerina'},{random_word: 'bases'},
    {random_word: 'backfire'},{random_word: 'backgammon'},{random_word: 'background'},{random_word: 'backgrounder'},{random_word: 'backgrounders'},{random_word: 'backgrounding'},{random_word: 'backhand'},{random_word: 'backhanded'},{random_word: 'backing'},{random_word: 'backlash'},{random_word: 'backlight'},{random_word: 'bail'},{random_word: 'banderilleros'},{random_word: 'barney'},{random_word: 'beau'},
    {random_word: 'backlog'},{random_word: 'backpack'},{random_word: 'backpedalling'},{random_word: 'backroom'},{random_word: 'backscatter'},{random_word: 'backscattered'},{random_word: 'backscattering'},{random_word: 'backscatterings'},{random_word: 'backside'},{random_word: 'backstabbings'},{random_word: 'backwardnesses'},{random_word: 'balkanizations'},{random_word: 'bankrupt'},{random_word: 'basement'},{random_word: 'been'},
    {random_word: 'backstage'},{random_word: 'backstitching'},{random_word: 'backstop'},{random_word: 'backstreet'},{random_word: 'backstretch'},{random_word: 'backstretches'},{random_word: 'backstroke'},{random_word: 'backtrack'},{random_word: 'backup'},{random_word: 'backward'},{random_word: 'bacteriological'},{random_word: 'banderillero'},{random_word: 'barbaric'},{random_word: 'bathroom'},{random_word: 'bug'},
    {random_word: 'backwater'},{random_word: 'backyard'},{random_word: 'bacon'},{random_word: 'bacteremia'},{random_word: 'bacteria'},{random_word: 'bacterial'},{random_word: 'bactericidally'},{random_word: 'bactericide'},{random_word: 'bacteriocin'},{random_word: 'bacteriologic'},{random_word: 'bah'},{random_word: 'banking'},{random_word: 'barn'},{random_word: 'beating'},{random_word: 'bureau'},
    {random_word: 'bacteriologies'},{random_word: 'bacteriologist'},{random_word: 'bacteriologists'},{random_word: 'bacteriology'},{random_word: 'bacteriolyses'},{random_word: 'bacteriolysis'},{random_word: 'bacteriolytic'},{random_word: 'bacteriophage'},{random_word: 'bacterium'},{random_word: 'baggage'},{random_word: 'balkanization'},{random_word: 'barbarianisms'},{random_word: 'baseman'},{random_word: 'beef'},{random_word: 'businessman'},
    {random_word: 'bacteriophages'},{random_word: 'bacteriophagies'},{random_word: 'bacteriophagy'},{random_word: 'bacteriostases'},{random_word: 'bacteriostasis'},{random_word: 'bacteriostat'},{random_word: 'bacteriostatic'},{random_word: 'bacteriostats'},{random_word: 'bag'},{random_word: 'balefulnesses'},{random_word: 'ballplayer'},{random_word: 'barlow'},{random_word: 'bath'},{random_word: 'behaviorism'},{random_word: 'byte'},
    {random_word: 'bacteriuria'},{random_word: 'bacterization'},{random_word: 'bacterizations'},{random_word: 'bad'},{random_word: 'badge'},{random_word: 'badger'},{random_word: 'badly'},{random_word: 'badminton'},{random_word: 'bale'},{random_word: 'ballpark'},{random_word: 'band'},{random_word: 'barrelhouse'},{random_word: 'beaten'},{random_word: 'bluebird'},
    {random_word: 'baked'},{random_word: 'baker'},{random_word: 'bakery'},{random_word: 'bal'},{random_word: 'balance'},{random_word: 'balcony'},{random_word: 'bald'},{random_word: 'balderdash'},{random_word: 'ballot'},{random_word: 'bananas'},{random_word: 'banker'},{random_word: 'baseless'},{random_word: 'beech'},{random_word: 'boardinghouses'},
    {random_word: 'ballet'},{random_word: 'balletomane'},{random_word: 'balletomanias'},{random_word: 'ballhandlings'},{random_word: 'ballistic'},{random_word: 'ballistically'},{random_word: 'ballistics'},{random_word: 'balloon'},{random_word: 'banana'},{random_word: 'bankcard'},{random_word: 'barbarian'},{random_word: 'batch'},{random_word: 'behavior'},{random_word: 'boilermaker'},
    {random_word: 'ballroom'},{random_word: 'balustrade'},{random_word: 'bam'},{random_word: 'bamboo'},{random_word: 'bamboozlement'},{random_word: 'bamboozlements'},{random_word: 'ban'},{random_word: 'banality'},{random_word: 'bankable'},{random_word: 'bar'},{random_word: 'bard'},{random_word: 'battle'},{random_word: 'bell'},{random_word: 'bos'},
    {random_word: 'bandleader'},{random_word: 'bandstand'},{random_word: 'bandwagon'},{random_word: 'bandwidth'},{random_word: 'bang'},{random_word: 'bangkok'},{random_word: 'bank'},{random_word: 'bankabilities'},{random_word: 'baptistery'},{random_word: 'barbiturate'},{random_word: 'barley'},{random_word: 'beachhead'},{random_word: 'ben'},{random_word: 'brachycephalic'},
    {random_word: 'banner'},{random_word: 'bannister'},{random_word: 'banquet'},{random_word: 'bans'},{random_word: 'bantamweight'},{random_word: 'bantamweights'},{random_word: 'bap'},{random_word: 'baptism'},{random_word: 'barbershop'},{random_word: 'barker'},{random_word: 'barrel'},{random_word: 'beat'},{random_word: 'betweenbrain'},{random_word: 'buffet'},
    {random_word: 'barbarism'},{random_word: 'barbarization'},{random_word: 'barbarizations'},{random_word: 'barbarous'},{random_word: 'barbarousness'},{random_word: 'barbarousnesses'},{random_word: 'barbecue'},{random_word: 'barber'},{random_word: 'bark'},{random_word: 'barred'},{random_word: 'baseball'},{random_word: 'become'},{random_word: 'bibliographies'},{random_word: 'bulletproof'},
    {random_word: 'bare'},{random_word: 'barefacedness'},{random_word: 'barefacednesses'},{random_word: 'barefoot'},{random_word: 'barely'},{random_word: 'bargain'},{random_word: 'barge'},{random_word: 'baritone'},{random_word: 'barrage'},{random_word: 'base'},{random_word: 'bat'},{random_word: 'bee'},{random_word: 'bituminization'},{random_word: 'burdensome'},
    {random_word: 'barometer'},{random_word: 'barometrically'},{random_word: 'baron'},{random_word: 'baroness'},{random_word: 'baroque'},{random_word: 'baroreceptor'},{random_word: 'baroreceptors'},{random_word: 'barquentine'},{random_word: 'basal'},{random_word: 'basifications'},{random_word: 'batting'},{random_word: 'behave'},{random_word: 'blitz'},{random_word: 'businesslike'},
    {random_word: 'barren'},{random_word: 'barricade'},{random_word: 'barrier'},{random_word: 'barring'},{random_word: 'barrister'},{random_word: 'barrow'},{random_word: 'bartender'},{random_word: 'bas'},{random_word: 'basidiospores'},{random_word: 'bastardizations'},{random_word: 'beachfront'},{random_word: 'believe'},{random_word: 'bloodcurdling'},{random_word: 'bystander'},
    {random_word: 'bash'},{random_word: 'bashfulnesses'},{random_word: 'basic'},{random_word: 'basically'},{random_word: 'basidiomycete'},{random_word: 'basidiomycetes'},{random_word: 'basidiomycetous'},{random_word: 'basidiospore'},{random_word: 'bastardization'},{random_word: 'battery'},{random_word: 'beast'},{random_word: 'belvedere'},{random_word: 'blue'},
    {random_word: 'basil'},{random_word: 'basilica'},{random_word: 'basin'},{random_word: 'basis'},{random_word: 'basket'},{random_word: 'basketball'},{random_word: 'bass'},{random_word: 'bastard'},{random_word: 'batter'},{random_word: 'beachcomber'},{random_word: 'beck'},{random_word: 'bes'},{random_word: 'board'},
    {random_word: 'bathymetrical'},{random_word: 'bathymetrically'},{random_word: 'bathypelagic'},{random_word: 'bathyscaphe'},{random_word: 'bathysphere'},{random_word: 'baton'},{random_word: 'bats'},{random_word: 'battalion'},{random_word: 'beach'},{random_word: 'bearing'},{random_word: 'bedtime'},{random_word: 'between'},{random_word: 'bodhisattva'},
    {random_word: 'battlefield'},{random_word: 'battlefront'},{random_word: 'battleground'},{random_word: 'battlegrounds'},{random_word: 'battleship'},{random_word: 'battlewagon'},{random_word: 'bay'},{random_word: 'be'},{random_word: 'beardtongue'},{random_word: 'because'},{random_word: 'behalf'},{random_word: 'bibliographical'},{random_word: 'boiler'},
    {random_word: 'beacon'},{random_word: 'bead'},{random_word: 'beam'},{random_word: 'bean'},{random_word: 'bear'},{random_word: 'bearable'},{random_word: 'bearbaiting'},{random_word: 'beard'},{random_word: 'became'},{random_word: 'bedside'},{random_word: 'believable'},{random_word: 'billingsgate'},{random_word: 'bond'},
    {random_word: 'beauteousnesses'},{random_word: 'beautician'},{random_word: 'beautifications'},{random_word: 'beautiful'},{random_word: 'beautifulnesses'},{random_word: 'beauty'},{random_word: 'beaver'},{random_word: 'beaverboard'},{random_word: 'bedroom'},{random_word: 'begun'},{random_word: 'belt'},{random_word: 'binary'},{random_word: 'bookbindery'},
    {random_word: 'becoming'},{random_word: 'bed'},{random_word: 'bedchamber'},{random_word: 'bedclothes'},{random_word: 'bedding'},{random_word: 'bedraggled'},{random_word: 'bedridden'},{random_word: 'bedrock'},{random_word: 'beginning'},{random_word: 'believabilities'},{random_word: 'benefactress'},{random_word: 'bioactivity'},{random_word: 'borrowing'},
    {random_word: 'beer'},{random_word: 'befitting'},{random_word: 'before'},{random_word: 'beforehand'},{random_word: 'beg'},{random_word: 'began'},{random_word: 'begin'},{random_word: 'beginner'},{random_word: 'belief'},{random_word: 'bellows'},{random_word: 'benzimidazole'},{random_word: 'bis'},{random_word: 'bottlenecked'},
    {random_word: 'behaviour'},{random_word: 'behemoth'},{random_word: 'behind'},{random_word: 'beholden'},{random_word: 'being'},{random_word: 'bejeweled'},{random_word: 'bel'},{random_word: 'belatednesses'},{random_word: 'belligerently'},{random_word: 'belowground'},{random_word: 'beryllium'},{random_word: 'bittersweetness'},{random_word: 'bracelet'},
    {random_word: 'belladonna'},{random_word: 'belle'},{random_word: 'bellflower'},{random_word: 'bellicosities'},{random_word: 'belligerence'},{random_word: 'belligerences'},{random_word: 'belligerency'},{random_word: 'belligerent'},{random_word: 'below'},{random_word: 'benefactor'},{random_word: 'betterment'},{random_word: 'blah'},{random_word: 'breadbasket'},
    {random_word: 'bellwether'},{random_word: 'belly'},{random_word: 'belong'},{random_word: 'belonging'},{random_word: 'belongingness'},{random_word: 'belongingnesses'},{random_word: 'belongings'},{random_word: 'beloved'},{random_word: 'benefaction'},{random_word: 'benevolence'},{random_word: 'bibliographers'},{random_word: 'blistering'},{random_word: 'brick'},
    {random_word: 'bench'},{random_word: 'benchmark'},{random_word: 'benchmarkings'},{random_word: 'benchwarmer'},{random_word: 'bend'},{random_word: 'beneath'},{random_word: 'benedict'},{random_word: 'benediction'},{random_word: 'benefit'},{random_word: 'benzanthracenes'},{random_word: 'bidialectalism'},{random_word: 'blood'},{random_word: 'browse'},
    {random_word: 'beneficence'},{random_word: 'beneficent'},{random_word: 'beneficial'},{random_word: 'beneficiaries'},{random_word: 'beneficiary'},{random_word: 'beneficiate'},{random_word: 'beneficiating'},{random_word: 'beneficiation'},{random_word: 'benzaldehydes'},{random_word: 'berth'},{random_word: 'bike'},{random_word: 'blowout'},{random_word: 'bubble'},
    {random_word: 'benevolent'},{random_word: 'benightedness'},{random_word: 'benightednesses'},{random_word: 'benign'},{random_word: 'benjamin'},{random_word: 'benny'},{random_word: 'bent'},{random_word: 'benzaldehyde'},{random_word: 'berry'},{random_word: 'better'},{random_word: 'billing'},{random_word: 'boar'},{random_word: 'buffer'},
    {random_word: 'benzoapyrenes'},{random_word: 'benzodiazepine'},{random_word: 'benzodiazepines'},{random_word: 'benzophenone'},{random_word: 'benzophenones'},{random_word: 'bereaved'},{random_word: 'berg'},{random_word: 'berlin'},{random_word: 'beth'},{random_word: 'bewilderments'},{random_word: 'bin'},{random_word: 'bode'},{random_word: 'bulletin'},
    {random_word: 'beside'},{random_word: 'besides'},{random_word: 'bespectacled'},{random_word: 'best'},{random_word: 'bestiality'},{random_word: 'bestsellerdom'},{random_word: 'bet'},{random_word: 'beta'},{random_word: 'bewilderment'},{random_word: 'bibliographer'},{random_word: 'bioactive'},{random_word: 'boiled'},{random_word: 'bumptiousness'},
    {random_word: 'betweenbrains'},{random_word: 'betweennesses'},{random_word: 'betweentimes'},{random_word: 'betweenwhiles'},{random_word: 'beverage'},{random_word: 'beware'},{random_word: 'bewhiskered'},{random_word: 'bewilderingly'},{random_word: 'biblical'},{random_word: 'bidialectal'},{random_word: 'birthright'},{random_word: 'bonanza'},{random_word: 'burden'},
    {random_word: 'bewitchment'},{random_word: 'bey'},{random_word: 'beyond'},{random_word: 'bi'},{random_word: 'biannual'},{random_word: 'bias'},{random_word: 'biased'},{random_word: 'bib'},{random_word: 'bibliotherapy'},{random_word: 'bigheartedness'},{random_word: 'bittersweet'},{random_word: 'book'},{random_word: 'business'},
    {random_word: 'bibliography'},{random_word: 'bibliolatry'},{random_word: 'bibliomania'},{random_word: 'bibliomaniacal'},{random_word: 'bibliophile'},{random_word: 'bibliophilisms'},{random_word: 'bibliotheca'},{random_word: 'bibliotherapies'},{random_word: 'bidding'},{random_word: 'billiards'},{random_word: 'blackboard'},{random_word: 'boost'},{random_word: 'butterball'},
    {random_word: 'bibulousnesses'},{random_word: 'bicarbonate'},{random_word: 'bicentenary'},{random_word: 'bicentennial'},{random_word: 'bicultural'},{random_word: 'biculturalisms'},{random_word: 'bicycle'},{random_word: 'bid'},{random_word: 'big'},{random_word: 'bimorphemic'},{random_word: 'blade'},{random_word: 'border'},{random_word: 'bys'},
    {random_word: 'bidialectalisms'},{random_word: 'bidirectional'},{random_word: 'bidirectionally'},{random_word: 'biennale'},{random_word: 'biennial'},{random_word: 'biennium'},{random_word: 'biflagellate'},{random_word: 'bifunctional'},{random_word: 'billiard'},{random_word: 'bioacoustics'},{random_word: 'blasphemous'},{random_word: 'borrow'}
    
];

const seedBooks = () => Random.bulkCreate(randomData);

module.exports = seedBooks;
